name: Generer la javadoc

on:
  push:
    branches:
      - master

jobs:
  publish-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Generate Javadoc
        run: mvn javadoc:javadoc
      - name: Publish Javadoc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs/
        permissions:
          contents: write
