name: Build une release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set Maven version
        run: mvn versions:set -DnewVersion=$GITHUB_REF_NAME -DgenerateBackupPoms=false

      - name: Build jar
        run: mvn package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/EditeurDeTexte-${{ env.GITHUB_REF_NAME }}.jar
          token: ${{ secrets.GITHUB_TOKEN }}
